steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "Instalando dependencias..."
      - name: Run Build
        run: echo "Compilando o projeto..."
      - name: Evidence for Professor (Docker PS)
        run: docker ps
